/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CompletionState {
  'may' : Array<DayEntries>,
  'march' : Array<DayEntries>,
  'april' : Array<DayEntries>,
  'november' : Array<DayEntries>,
  'july' : Array<DayEntries>,
  'june' : Array<DayEntries>,
  'february' : Array<DayEntries>,
  'september' : Array<DayEntries>,
  'august' : Array<DayEntries>,
  'january' : Array<DayEntries>,
  'october' : Array<DayEntries>,
  'december' : Array<DayEntries>,
}
export interface DayEntries { 'day' : bigint, 'completed' : boolean }
export interface Habit {
  'id' : bigint,
  'completion' : CompletionState,
  'volumeTracking' : [] | [VolumeTracking],
  'reminder' : [] | [Time],
  'name' : string,
  'description' : string,
}
export type Time = bigint;
export interface TimeVolumeEntry {
  'minutes' : [] | [bigint],
  'timeString' : [] | [string],
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VolumeTracking {
  'unitType' : string,
  'may' : TimeVolumeEntry,
  'march' : TimeVolumeEntry,
  'april' : TimeVolumeEntry,
  'november' : TimeVolumeEntry,
  'july' : TimeVolumeEntry,
  'june' : TimeVolumeEntry,
  'february' : TimeVolumeEntry,
  'september' : TimeVolumeEntry,
  'august' : TimeVolumeEntry,
  'january' : TimeVolumeEntry,
  'october' : TimeVolumeEntry,
  'december' : TimeVolumeEntry,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addHabit' : ActorMethod<[string, string, [] | [Time]], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getHabits' : ActorMethod<[], Array<Habit>>,
  'getTotalHabitsCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'toggleCompletion' : ActorMethod<
    [bigint, bigint, bigint, boolean],
    undefined
  >,
  'updateHabit' : ActorMethod<[bigint, string, string, [] | [Time]], undefined>,
  'updateHabitUnitType' : ActorMethod<[bigint, string], undefined>,
  'updateHabitVolume' : ActorMethod<
    [bigint, bigint, TimeVolumeEntry],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];