/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CompletionState {
    may: Array<DayEntries>;
    march: Array<DayEntries>;
    april: Array<DayEntries>;
    november: Array<DayEntries>;
    july: Array<DayEntries>;
    june: Array<DayEntries>;
    february: Array<DayEntries>;
    september: Array<DayEntries>;
    august: Array<DayEntries>;
    january: Array<DayEntries>;
    october: Array<DayEntries>;
    december: Array<DayEntries>;
}
export type Time = bigint;
export interface DayEntries {
    day: bigint;
    completed: boolean;
}
export interface TimeZone {
    name: string;
    utcOffsetMinutes: bigint;
}
export interface Habit {
    id: bigint;
    completion: CompletionState;
    volumeTracking?: VolumeTracking;
    reminder?: Time;
    name: string;
    description: string;
}
export interface VolumeTracking {
    unitType: string;
    may: TimeVolumeEntry;
    march: TimeVolumeEntry;
    april: TimeVolumeEntry;
    november: TimeVolumeEntry;
    july: TimeVolumeEntry;
    june: TimeVolumeEntry;
    february: TimeVolumeEntry;
    september: TimeVolumeEntry;
    august: TimeVolumeEntry;
    january: TimeVolumeEntry;
    october: TimeVolumeEntry;
    december: TimeVolumeEntry;
}
export interface UserProfile {
    name: string;
}
export interface TimeVolumeEntry {
    minutes?: bigint;
    timeString?: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addHabit(name: string, description: string, reminder: Time | null): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getCallerTimeZone(): Promise<TimeZone | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getHabits(): Promise<Array<Habit>>;
    getTodaysQuote(): Promise<string>;
    getTotalHabitsCount(): Promise<bigint>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setUserTimeZone(timeZone: TimeZone): Promise<void>;
    toggleCompletion(habitId: bigint, month: bigint, day: bigint, completed: boolean): Promise<void>;
    updateHabit(habitId: bigint, name: string, description: string, reminder: Time | null): Promise<void>;
    updateHabitUnitType(habitId: bigint, unitType: string): Promise<void>;
    updateHabitVolume(habitId: bigint, monthIndex: bigint, entry: TimeVolumeEntry): Promise<void>;
}
import type { CompletionState as _CompletionState, Habit as _Habit, Time as _Time, TimeVolumeEntry as _TimeVolumeEntry, TimeZone as _TimeZone, UserProfile as _UserProfile, UserRole as _UserRole, VolumeTracking as _VolumeTracking } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addHabit(arg0: string, arg1: string, arg2: Time | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addHabit(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addHabit(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n2(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n2(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getCallerTimeZone(): Promise<TimeZone | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerTimeZone();
                return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerTimeZone();
            return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHabits(): Promise<Array<Habit>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHabits();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHabits();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTodaysQuote(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getTodaysQuote();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTodaysQuote();
            return result;
        }
    }
    async getTotalHabitsCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalHabitsCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalHabitsCount();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setUserTimeZone(arg0: TimeZone): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setUserTimeZone(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUserTimeZone(arg0);
            return result;
        }
    }
    async toggleCompletion(arg0: bigint, arg1: bigint, arg2: bigint, arg3: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleCompletion(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleCompletion(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateHabit(arg0: bigint, arg1: string, arg2: string, arg3: Time | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHabit(arg0, arg1, arg2, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHabit(arg0, arg1, arg2, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async updateHabitUnitType(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHabitUnitType(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHabitUnitType(arg0, arg1);
            return result;
        }
    }
    async updateHabitVolume(arg0: bigint, arg1: bigint, arg2: TimeVolumeEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHabitVolume(arg0, arg1, to_candid_TimeVolumeEntry_n19(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHabitVolume(arg0, arg1, to_candid_TimeVolumeEntry_n19(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
}
function from_candid_Habit_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Habit): Habit {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_TimeVolumeEntry_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TimeVolumeEntry): TimeVolumeEntry {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_VolumeTracking_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VolumeTracking): VolumeTracking {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_VolumeTracking]): VolumeTracking | null {
    return value.length === 0 ? null : from_candid_VolumeTracking_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TimeZone]): TimeZone | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    completion: _CompletionState;
    volumeTracking: [] | [_VolumeTracking];
    reminder: [] | [_Time];
    name: string;
    description: string;
}): {
    id: bigint;
    completion: CompletionState;
    volumeTracking?: VolumeTracking;
    reminder?: Time;
    name: string;
    description: string;
} {
    return {
        id: value.id,
        completion: value.completion,
        volumeTracking: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.volumeTracking)),
        reminder: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.reminder)),
        name: value.name,
        description: value.description
    };
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    unitType: string;
    may: _TimeVolumeEntry;
    march: _TimeVolumeEntry;
    april: _TimeVolumeEntry;
    november: _TimeVolumeEntry;
    july: _TimeVolumeEntry;
    june: _TimeVolumeEntry;
    february: _TimeVolumeEntry;
    september: _TimeVolumeEntry;
    august: _TimeVolumeEntry;
    january: _TimeVolumeEntry;
    october: _TimeVolumeEntry;
    december: _TimeVolumeEntry;
}): {
    unitType: string;
    may: TimeVolumeEntry;
    march: TimeVolumeEntry;
    april: TimeVolumeEntry;
    november: TimeVolumeEntry;
    july: TimeVolumeEntry;
    june: TimeVolumeEntry;
    february: TimeVolumeEntry;
    september: TimeVolumeEntry;
    august: TimeVolumeEntry;
    january: TimeVolumeEntry;
    october: TimeVolumeEntry;
    december: TimeVolumeEntry;
} {
    return {
        unitType: value.unitType,
        may: from_candid_TimeVolumeEntry_n14(_uploadFile, _downloadFile, value.may),
        march: from_candid_TimeVolumeEntry_n14(_uploadFile, _downloadFile, value.march),
        april: from_candid_TimeVolumeEntry_n14(_uploadFile, _downloadFile, value.april),
        november: from_candid_TimeVolumeEntry_n14(_uploadFile, _downloadFile, value.november),
        july: from_candid_TimeVolumeEntry_n14(_uploadFile, _downloadFile, value.july),
        june: from_candid_TimeVolumeEntry_n14(_uploadFile, _downloadFile, value.june),
        february: from_candid_TimeVolumeEntry_n14(_uploadFile, _downloadFile, value.february),
        september: from_candid_TimeVolumeEntry_n14(_uploadFile, _downloadFile, value.september),
        august: from_candid_TimeVolumeEntry_n14(_uploadFile, _downloadFile, value.august),
        january: from_candid_TimeVolumeEntry_n14(_uploadFile, _downloadFile, value.january),
        october: from_candid_TimeVolumeEntry_n14(_uploadFile, _downloadFile, value.october),
        december: from_candid_TimeVolumeEntry_n14(_uploadFile, _downloadFile, value.december)
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    minutes: [] | [bigint];
    timeString: [] | [string];
}): {
    minutes?: bigint;
    timeString?: string;
} {
    return {
        minutes: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.minutes)),
        timeString: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.timeString))
    };
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Habit>): Array<Habit> {
    return value.map((x)=>from_candid_Habit_n9(_uploadFile, _downloadFile, x));
}
function to_candid_TimeVolumeEntry_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TimeVolumeEntry): _TimeVolumeEntry {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Time | null): [] | [_Time] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    minutes?: bigint;
    timeString?: string;
}): {
    minutes: [] | [bigint];
    timeString: [] | [string];
} {
    return {
        minutes: value.minutes ? candid_some(value.minutes) : candid_none(),
        timeString: value.timeString ? candid_some(value.timeString) : candid_none()
    };
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
