/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TimeZone = IDL.Record({
  'name' : IDL.Text,
  'utcOffsetMinutes' : IDL.Int,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const DayEntries = IDL.Record({
  'day' : IDL.Nat,
  'completed' : IDL.Bool,
});
export const CompletionState = IDL.Record({
  'may' : IDL.Vec(DayEntries),
  'march' : IDL.Vec(DayEntries),
  'april' : IDL.Vec(DayEntries),
  'november' : IDL.Vec(DayEntries),
  'july' : IDL.Vec(DayEntries),
  'june' : IDL.Vec(DayEntries),
  'february' : IDL.Vec(DayEntries),
  'september' : IDL.Vec(DayEntries),
  'august' : IDL.Vec(DayEntries),
  'january' : IDL.Vec(DayEntries),
  'october' : IDL.Vec(DayEntries),
  'december' : IDL.Vec(DayEntries),
});
export const TimeVolumeEntry = IDL.Record({
  'minutes' : IDL.Opt(IDL.Nat),
  'timeString' : IDL.Opt(IDL.Text),
});
export const VolumeTracking = IDL.Record({
  'unitType' : IDL.Text,
  'may' : TimeVolumeEntry,
  'march' : TimeVolumeEntry,
  'april' : TimeVolumeEntry,
  'november' : TimeVolumeEntry,
  'july' : TimeVolumeEntry,
  'june' : TimeVolumeEntry,
  'february' : TimeVolumeEntry,
  'september' : TimeVolumeEntry,
  'august' : TimeVolumeEntry,
  'january' : TimeVolumeEntry,
  'october' : TimeVolumeEntry,
  'december' : TimeVolumeEntry,
});
export const Habit = IDL.Record({
  'id' : IDL.Nat,
  'completion' : CompletionState,
  'volumeTracking' : IDL.Opt(VolumeTracking),
  'reminder' : IDL.Opt(Time),
  'name' : IDL.Text,
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addHabit' : IDL.Func([IDL.Text, IDL.Text, IDL.Opt(Time)], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerTimeZone' : IDL.Func([], [IDL.Opt(TimeZone)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getHabits' : IDL.Func([], [IDL.Vec(Habit)], ['query']),
  'getTodaysQuote' : IDL.Func([], [IDL.Text], ['query']),
  'getTotalHabitsCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setUserTimeZone' : IDL.Func([TimeZone], [], []),
  'toggleCompletion' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat, IDL.Bool], [], []),
  'updateHabit' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Opt(Time)],
      [],
      [],
    ),
  'updateHabitUnitType' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateHabitVolume' : IDL.Func([IDL.Nat, IDL.Nat, TimeVolumeEntry], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TimeZone = IDL.Record({
    'name' : IDL.Text,
    'utcOffsetMinutes' : IDL.Int,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const DayEntries = IDL.Record({ 'day' : IDL.Nat, 'completed' : IDL.Bool });
  const CompletionState = IDL.Record({
    'may' : IDL.Vec(DayEntries),
    'march' : IDL.Vec(DayEntries),
    'april' : IDL.Vec(DayEntries),
    'november' : IDL.Vec(DayEntries),
    'july' : IDL.Vec(DayEntries),
    'june' : IDL.Vec(DayEntries),
    'february' : IDL.Vec(DayEntries),
    'september' : IDL.Vec(DayEntries),
    'august' : IDL.Vec(DayEntries),
    'january' : IDL.Vec(DayEntries),
    'october' : IDL.Vec(DayEntries),
    'december' : IDL.Vec(DayEntries),
  });
  const TimeVolumeEntry = IDL.Record({
    'minutes' : IDL.Opt(IDL.Nat),
    'timeString' : IDL.Opt(IDL.Text),
  });
  const VolumeTracking = IDL.Record({
    'unitType' : IDL.Text,
    'may' : TimeVolumeEntry,
    'march' : TimeVolumeEntry,
    'april' : TimeVolumeEntry,
    'november' : TimeVolumeEntry,
    'july' : TimeVolumeEntry,
    'june' : TimeVolumeEntry,
    'february' : TimeVolumeEntry,
    'september' : TimeVolumeEntry,
    'august' : TimeVolumeEntry,
    'january' : TimeVolumeEntry,
    'october' : TimeVolumeEntry,
    'december' : TimeVolumeEntry,
  });
  const Habit = IDL.Record({
    'id' : IDL.Nat,
    'completion' : CompletionState,
    'volumeTracking' : IDL.Opt(VolumeTracking),
    'reminder' : IDL.Opt(Time),
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addHabit' : IDL.Func([IDL.Text, IDL.Text, IDL.Opt(Time)], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerTimeZone' : IDL.Func([], [IDL.Opt(TimeZone)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getHabits' : IDL.Func([], [IDL.Vec(Habit)], ['query']),
    'getTodaysQuote' : IDL.Func([], [IDL.Text], ['query']),
    'getTotalHabitsCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setUserTimeZone' : IDL.Func([TimeZone], [], []),
    'toggleCompletion' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Bool],
        [],
        [],
      ),
    'updateHabit' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Opt(Time)],
        [],
        [],
      ),
    'updateHabitUnitType' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateHabitVolume' : IDL.Func([IDL.Nat, IDL.Nat, TimeVolumeEntry], [], []),
  });
};

export const init = ({ IDL }) => { return []; };